import re

def contains_unicode_math(text):
    """Return True if any unsafe Unicode math characters are found."""
    bad_chars = ['√', '∫', '−', '²', '³']
    return any(char in text for char in bad_chars)

def super_fix_latex(text):
    r"""
    Clean and repair the LaTeX questions generated by the LLM.
    """

    # Merge broken lines inside \item
    lines = []
    buffer = ""

    for line in text.splitlines():
        if line.strip().startswith(r"\item"):
            if buffer:
                lines.append(buffer.strip())
            buffer = line.strip()
        else:
            buffer += " " + line.strip()

    if buffer:
        lines.append(buffer.strip())

    # After each item, add vertical space
    fixed_lines = []
    for line in lines:
        fixed_lines.append(line)
        fixed_lines.append(r"\vspace{2cm}")  # Add 2cm of space after each question

    fixed_text = "\n".join(fixed_lines)

    # Replace Unicode characters
    replacements = {
        '√': r'\sqrt{}',
        '∫': r'\int',
        '−': '-',  # Unicode minus
        '²': '^{2}',
        '³': '^{3}',
    }
    for bad_char, replacement in replacements.items():
        fixed_text = fixed_text.replace(bad_char, replacement)

    # Remove double spaces
    fixed_text = re.sub(r'\s+', ' ', fixed_text)

    return fixed_text


import re

def clean_llm_output(text):
    """Clean LLM output by removing any intro before first \item and fixing inline math."""
    # Find first \item
    first_item_index = text.find(r"\item")
    if first_item_index != -1:
        text = text[first_item_index:]  # Keep only from first \item onward

    text = text.replace("\\(", "$").replace("\\)", "$")
    return text

